#!/usr/bin/env python3
# Copyright (c) Muse Pocket contributors. Licensed under Apache-2.0.
"""Generate the OFL-derived flash bitmap; see README.md for pinned environment."""
import argparse
import hashlib
import json
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont, ImageOps, features
import PIL
from fontTools.ttLib import TTFont
import fontTools

ROOT = Path(__file__).resolve().parents[2]
SOURCE_URL = "https://raw.githubusercontent.com/notofonts/noto-cjk/f8d157532fbfaeda587e826d4cd5b21a49186f7c/Sans/OTF/SimplifiedChinese/NotoSansCJKsc-Regular.otf"
SOURCE_SHA256 = "2c76254f6fc379fddfce0a7e84fb5385bb135d3e399294f6eeb6680d0365b74b"
RANGES = ((0x2010, 0x2027), (0x3000, 0x303F), (0x4E00, 0x9FFF), (0xFF00, 0xFFEF))
VERSIONS = {"Pillow": "10.4.0", "fontTools": "4.59.1", "FreeType": "2.13.2"}


def rasterize(font, cp):
    # A padded surface preserves marks outside the nominal advance and baseline.
    canvas = Image.new("L", (96, 96))
    ImageDraw.Draw(canvas).text((32, 45), chr(cp), font=font, fill=255, anchor="ls", stroke_width=0)
    mono = canvas.point(lambda v: 255 if v >= 96 else 0, mode="1")
    bbox = mono.getbbox()
    cell = Image.new("1", (16, 16))
    adjusted = False
    if bbox:
        ink = mono.crop(bbox)
        x, y = bbox[0] - 32, bbox[1] - 32
        w, h = ink.size
        if w > 16 or h > 16:
            scale = min(16 / w, 16 / h)
            ink = ink.resize((max(1, int(w * scale)), max(1, int(h * scale))), Image.Resampling.NEAREST)
            w, h = ink.size
            adjusted = True
        nx, ny = min(max(x, 0), 16 - w), min(max(y, 0), 16 - h)
        adjusted |= (nx, ny) != (x, y)
        cell.paste(ink, (nx, ny))
    # Explicit row-major, bit 7 at the left edge of each byte.
    data = bytes(sum((1 << (7 - bit)) if cell.getpixel((byte * 8 + bit, row)) else 0 for bit in range(8))
                 for row in range(16) for byte in range(2))
    return data, adjusted


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--font", type=Path, default=ROOT / "artifacts/fonts/NotoSansCJKsc-Regular.otf")
    parser.add_argument("--output-dir", type=Path, default=ROOT / "esp32/main/fonts")
    parser.add_argument("--preview", type=Path, default=ROOT / "artifacts/fonts/cjk-preview.png")
    args = parser.parse_args()
    versions = {"Pillow": PIL.__version__, "fontTools": fontTools.__version__, "FreeType": features.version_module("freetype2")}
    if versions != VERSIONS:
        parser.error(f"Reproducibility requires {VERSIONS}; found {versions}")
    if hashlib.sha256(args.font.read_bytes()).hexdigest() != SOURCE_SHA256:
        parser.error("Source font SHA256 mismatch")
    cmap = TTFont(args.font).getBestCmap()
    cps = [cp for first, last in RANGES for cp in range(first, last + 1) if cp in cmap and cmap[cp] != ".notdef"]
    font = ImageFont.truetype(str(args.font), size=15, layout_engine=ImageFont.Layout.BASIC)
    glyphs, adjusted, blank = [], [], []
    for cp in cps:
        data, changed = rasterize(font, cp)
        glyphs.append(data)
        if changed:
            adjusted.append(cp)
        if not any(data):
            blank.append(cp)
    args.output_dir.mkdir(parents=True, exist_ok=True)
    lines = ["// Generated by tools/fonts/generate_cjk.py. Do not edit.",
             "// Derived from Noto Sans CJK SC; SIL OFL 1.1, see OFL.txt and README.md.",
             "static const uint16_t kCjkCodepoints[] = {"]
    for i in range(0, len(cps), 12):
        lines.append("    " + ", ".join(f"0x{cp:04x}" for cp in cps[i:i + 12]) + ",")
    lines.extend(["};", "static const uint8_t kCjkBitmaps[][32] = {"])
    lines.extend("    {" + ",".join(f"0x{v:02x}" for v in data) + "}," for data in glyphs)
    lines.extend(["};", ""])
    (args.output_dir / "pocket_cjk_data.inc").write_text("\n".join(lines))
    metadata = {"source_url": SOURCE_URL, "source_sha256": SOURCE_SHA256, "versions": versions,
                "ranges": [[f"U+{a:04X}", f"U+{b:04X}"] for a, b in RANGES],
                "glyph_count": len(cps), "bitmap_bytes": len(cps) * 32, "index_bytes": len(cps) * 2,
                "bitmap_sha256": hashlib.sha256(b"".join(glyphs)).hexdigest(),
                "blank_codepoints": [f"U+{cp:04X}" for cp in blank],
                "missing_codepoints": [f"U+{cp:04X}" for a, b in RANGES for cp in range(a, b + 1) if cp not in cps],
                "adjusted_count": len(adjusted),
                "adjusted_codepoints": [f"U+{cp:04X}" for cp in adjusted],
                "parameters": {"font_size": 15, "cell": [16, 16], "baseline": 13, "threshold": 96,
                               "layout": "BASIC", "packing": "row-major MSB-first", "fit": "clamp ink; nearest shrink only oversized glyphs"}}
    (args.output_dir / "metadata.json").write_text(json.dumps(metadata, indent=2) + "\n")
    preview_text = "中文显示你好世界状态连接设置恢复国鬱，。！？（）　他说：“你好……”"
    preview = Image.new("RGB", (12 * 64, 3 * 88), "#dddddd")
    draw = ImageDraw.Draw(preview)
    for index, ch in enumerate(preview_text):
        cp = ord(ch)
        bits = glyphs[cps.index(cp)]
        tile = Image.frombytes("1", (16, 16), bits).resize((64, 64), Image.Resampling.NEAREST)
        tile = tile.convert("RGB")
        # Glyph bits are ink; display black ink on white paper.
        tile = ImageOps.invert(tile)
        x, y = (index % 12) * 64, (index // 12) * 88
        preview.paste(tile, (x, y))
        draw.text((x + 4, y + 66), f"{cp:04X}", fill="black")
    args.preview.parent.mkdir(parents=True, exist_ok=True)
    preview.save(args.preview)
    print(f"{len(cps)} glyphs, {len(cps) * 34} flash bytes; {len(blank)} blank, {len(adjusted)} fitted")


if __name__ == "__main__":
    main()
